apiVersion: v1
kind: ConfigMap
metadata:
  name: eshop-catalog-config
  labels:
    app.kubernetes.io/name: eshop-catalog
    app.kubernetes.io/part-of: eshop
    app.kubernetes.io/managed-by: kubectl
data:
  SPRING_PROFILES_ACTIVE: "prod"
  DB_URL: "jdbc:sqlserver://sqlserver-service:1433;databaseName=CatalogDb;encrypt=true;trustServerCertificate=true"
  USE_MOCK_DATA: "false"
  SERVER_PORT: "8080"
