-- V1__create_tables.sql
-- Create catalog schema tables matching the JPA entity mappings.

CREATE TABLE catalog_type (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        VARCHAR(100) NOT NULL
);

CREATE TABLE catalog_brand (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand       VARCHAR(100) NOT NULL
);

CREATE TABLE catalog (
    id                  INTEGER      NOT NULL PRIMARY KEY,
    name                VARCHAR(50)  NOT NULL,
    description         VARCHAR(255),
    price               DECIMAL(18,2) NOT NULL,
    picture_file_name   VARCHAR(255) NOT NULL,
    catalog_type_id     INTEGER      NOT NULL,
    catalog_brand_id    INTEGER      NOT NULL,
    available_stock     INTEGER      NOT NULL DEFAULT 0,
    restock_threshold   INTEGER      NOT NULL DEFAULT 0,
    max_stock_threshold INTEGER      NOT NULL DEFAULT 0,
    on_reorder          BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_catalog_type  FOREIGN KEY (catalog_type_id)  REFERENCES catalog_type(id),
    CONSTRAINT fk_catalog_brand FOREIGN KEY (catalog_brand_id) REFERENCES catalog_brand(id)
);
