<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>eShopLegacyMVC</RootNamespace>
    <AssemblyName>eShopLegacyMVC</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.11" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.22.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="log4net" Version="3.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\eShopLegacy.Utilities\eShopLegacy.Utilities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Models\Infrastructure\dbo.catalog_hilo.Sequence.sql" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Models\Infrastructure\dbo.catalog_brand_hilo.Sequence.sql" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Models\Infrastructure\dbo.catalog_type_hilo.Sequence.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
